export const GET_PRODUCT_EPIC = 'GET_PRODUCT_EPIC';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_INFINITE_SCROLL_LOADING =
  'GET_PRODUCT_INFINITE_SCROLL_LOADING';
export const GET_PRODUCT_CANCEL = 'GET_PRODUCT_CANCEL';
